import cv2
import face_recognition
import pickle
import os
import numpy as np
from datetime import datetime
import time
from attendance_manager import AttendanceManager
import math

class FaceRecognizer:
    def __init__(self, db_folder='database'):
        self.db_folder = db_folder
        self.encodings_file = os.path.join(db_folder, 'encodings.pickle')
        self.known_encodings = []
        self.known_names = []
        self.attendance_manager = AttendanceManager(db_folder=db_folder)
        self.last_unknown_save = 0
        self.liveness_record = {} # {name: {"blinks": 0, "status": "Checking..."}}
        
    def load_encodings(self):
        """Loads encodings generated by face_train.py."""
        if not os.path.exists(self.encodings_file):
            print(f"Error: {self.encodings_file} not found. Please train the system first.")
            return False
            
        with open(self.encodings_file, "rb") as f:
            data = pickle.load(f)
            self.known_encodings = data["encodings"]
            self.known_names = data["names"]
            
        return len(self.known_encodings) > 0

    def save_unknown_face(self, frame, location):
        """Saves unknown faces if we haven't saved one in the last 5 seconds."""
        current_time = time.time()
        if current_time - self.last_unknown_save > 5:
            unknown_dir = os.path.join(self.db_folder, 'unknown_faces')
            if not os.path.exists(unknown_dir):
                os.makedirs(unknown_dir)
                
            # Expand bounding box slightly for a better crop
            top, right, bottom, left = location
            h, w = frame.shape[:2]
            top = max(0, top - 20)
            right = min(w, right + 20)
            bottom = min(h, bottom + 20)
            left = max(0, left - 20)
            
            face_img = frame[top:bottom, left:right]
            
            if face_img.size > 0:
                filename = f"Unknown_{datetime.now().strftime('%Y%m%d_%H%M%S')}.jpg"
                filepath = os.path.join(unknown_dir, filename)
                cv2.imwrite(filepath, face_img)
                self.last_unknown_save = current_time

    def get_eye_aspect_ratio(self, eye_landmarks):
        # Compute distances between the vertical eye landmarks
        A = math.dist(eye_landmarks[1], eye_landmarks[5])
        B = math.dist(eye_landmarks[2], eye_landmarks[4])
        # Compute distance between the horizontal eye landmarks
        C = math.dist(eye_landmarks[0], eye_landmarks[3])
        ear = (A + B) / (2.0 * C)
        return ear

    def start_recognition(self):
        """Starts webcam feed, recognizes faces, and updates attendance."""
        if not self.known_encodings:
            if not self.load_encodings():
                return
                
        cap = cv2.VideoCapture(0)
        print("Starting webcam... Press 'q' to quit.")
        
        # Process every frame for liveness, but recognize every 2nd
        process_this_frame = True
        face_locations = []
        face_names = []
        
        while True:
            ret, frame = cap.read()
            if not ret: break
                
            rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            
            # 1. Face Recognition (on downscaled frame)
            if process_this_frame:
                small_frame = cv2.resize(rgb_frame, (0, 0), fx=0.25, fy=0.25)
                face_locations = face_recognition.face_locations(small_frame)
                face_encodings = face_recognition.face_encodings(small_frame, face_locations)
                
                face_names = []
                for encoding in face_encodings:
                    matches = face_recognition.compare_faces(self.known_encodings, encoding, tolerance=0.5)
                    name = "Unknown"
                    if any(matches):
                        best_match_index = np.argmin(face_recognition.face_distance(self.known_encodings, encoding))
                        name = self.known_names[best_match_index]
                    face_names.append(name)

            process_this_frame = not process_this_frame

            # 2. Liveness Detection (Blink detection)
            # Find landmarks in full resolution for accuracy
            face_landmarks_list = face_recognition.face_landmarks(rgb_frame)
            
            for (top, right, bottom, left), name, landmarks in zip(face_locations, face_names, face_landmarks_list):
                # Scale back locations
                top, right, bottom, left = top*4, right*4, bottom*4, left*4
                
                color = (0, 255, 0) if name != "Unknown" else (0, 0, 255)
                status_text = "Verifying..."

                if name != "Unknown":
                    if name not in self.liveness_record:
                        self.liveness_record[name] = {"blinks": 0, "verified": False}
                    
                    # Check Eye Aspect Ratio for blinks
                    left_ear = self.get_eye_aspect_ratio(landmarks['left_eye'])
                    right_ear = self.get_eye_aspect_ratio(landmarks['right_eye'])
                    ear = (left_ear + right_ear) / 2.0
                    
                    if ear < 0.2: # Eye closed
                        self.liveness_record[name]["verified"] = True
                    
                    if self.liveness_record[name]["verified"]:
                        success, arrival_status = self.attendance_manager.mark_attendance(name)
                        status_text = f"Live - {arrival_status}" if success else "Already Marked"
                    else:
                        status_text = "Blink to verify"
                else:
                    self.save_unknown_face(frame, (top, right, bottom, left))
                    status_text = "Intruder Alert"

                # UI
                cv2.rectangle(frame, (left, top), (right, bottom), color, 2)
                cv2.rectangle(frame, (left, bottom - 35), (right, bottom), color, cv2.FILLED)
                cv2.putText(frame, f"{name}: {status_text}", (left + 6, bottom - 6), 
                            cv2.FONT_HERSHEY_DUPLEX, 0.6, (255, 255, 255), 1)
                
            cv2.imshow('Smart Attendance - Real Time', frame)
            if cv2.waitKey(1) & 0xFF == ord('q'): break
                
        cap.release()
        cv2.destroyAllWindows()

if __name__ == "__main__":
    recognizer = FaceRecognizer()
    recognizer.start_recognition()
